GAP2/GAP.Frederik.SuperZapatos/Controllers/ArticleController.cs
using GAP.Frederik.SuperZapatos.BLL;
using GAP.Frederik.SuperZapatos.Common.Util.ErrorHandling;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GAP.Frederik.SuperZapatos.Controllers
{
    public class ArticleController : Controller
    {
        private IArticleBll _articleBll;

        public ArticleController(IArticleBll articleBll)
        {
            this._articleBll = articleBll;
        }

        // GET: Article
        public ActionResult Index()
        {
            ISystemResponse error = new SystemResponse();
            var stores = _articleBll.GetArticles(error);

            return View(stores);
        }
    }
}

GAP2/GAP.Frederik.SuperZapatos/Controllers/StoreController.cs
using GAP.Frederik.SuperZapatos.BLL;
using GAP.Frederik.SuperZapatos.Common.Util.ErrorHandling;
using GAP.Frederik.SuperZapatos.Model;
using GAP.Frederik.SuperZapatos.Model.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GAP.Frederik.SuperZapatos.Controllers
{
    public class StoreController : Controller
    {
        private  IStoreBll _storeBll;

        public StoreController(IStoreBll storeBll)
        {
            this._storeBll = storeBll;
        }

        // GET: Store
        public ActionResult Index()
        {
            ISystemResponse error = new SystemResponse();
            var stores = _storeBll.GetStores(error);

            return View(stores);
        }

        [HttpPost]
        public ActionResult Create(Store store)
        {
            bool created = false;
            ISystemResponse error = new SystemResponse();

            if (ModelState.IsValid)
            {
                created = _storeBll.CreateStore(store, error);

                if(created)
                    return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ISystemResponse error = new SystemResponse();
            StoreModel store = _storeBll.GetStore(id.Value, error);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

       
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ISystemResponse error = new SystemResponse();
            bool deleted = _storeBll.DeleteStore(id, error);

            if (deleted)
                return RedirectToAction("Index");

            return View();
        }

        //public ActionResult Update()
        //{
        //    ISystemResponse error = new SystemResponse();
        //    bool updated = _storeBll.
        //}

        public ActionResult Details(int id)
        {
            ISystemResponse error = new SystemResponse();
            var store = _storeBll.GetStore(id, error);

            return View(store);
        }

        public ActionResult Edit(int id)
        {
            ISystemResponse error = new SystemResponse();
            var store = _storeBll.GetStore(id, error);

            return View(store);
        }

        [HttpPost]
        public ActionResult Edit(StoreModel store)
        {
            ISystemResponse error = new SystemResponse();
            bool updated = _storeBll.UpdateStore(store, error);

            if (updated)
                return RedirectToAction("Index");

            return View();
        }
    }
}

GAP2/GAP.Frederik.SuperZapatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Super Zapatos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Stores", "Index", "Store")</li>
                    <li>@Html.ActionLink("Articles", "Index", "Article")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>